FROM node:22-alpine as build
# FROM dockerhub.timeweb.cloud/library/node:22-alpine as build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.25.5-alpine
# FROM dockerhub.timeweb.cloud/library/nginx:1.25.5-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD [ "nginx", "-g", "daemon off;" ]


# Have to create Docker image and push it to ghcr.io. 
# Can't run build with Docker Compose on VDS due to insufficient hardware (1GB RAM). Error: JavaScript heap out of memory.