services:
    init-dhparams:
        image: certbot/certbot
        restart: "no"
        entrypoint: /bin/sh
        command: -c 'test -f /etc/letsencrypt/ssl-dhparams.pem || openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 4096'
        volumes:
            - cert_volume:/etc/letsencrypt:Z

    certbot-oneshot:
        image: certbot/certbot
        restart: "no"
        entrypoint: /bin/sh
        command: -c 'test -d /etc/letsencrypt/live/${BASE_DOMAIN} || certbot certonly --standalone --register-unsafely-without-email -d ${BASE_DOMAIN} --rsa-key-size ${rsa_key_size:-2048} --agree-tos --force-renewal'
        ports:
            - "80:80"
        volumes:
            - cert_volume:/etc/letsencrypt:Z

    api:
        build: "./server"
        container_name: api
        env_file:
            - server/.env.production
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            init-dhparams:
                condition: service_completed_successfully
                required: true
            certbot-oneshot:
                condition: service_completed_successfully
                required: true

    nginx-react:
        # build: "./client"
        image: ghcr.io/civiaj/nginx-client:latest
        container_name: nginx-react
        # env_file:
        #     - client/.env.production.local
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        depends_on:
            init-dhparams:
                condition: service_completed_successfully
                required: true
            certbot-oneshot:
                condition: service_completed_successfully
                required: true
            api:
                condition: service_started
                required: true
        volumes:
            - cert_volume:/etc/letsencrypt:Z
            - acme_challenge:/usr/share/nginx/html/.well-known:Z

    certbot:
        image: certbot/certbot
        container_name: certbot
        command: -c 'trap exit TERM; while :; do certbot renew; sleep 24h && wait $${!}; done;'
        depends_on:
            nginx-react:
                condition: service_started
                required: true
        volumes:
            - cert_volume:/etc/letsencrypt:Z
            - acme_challenge:/usr/share/nginx/html/.well-known:Z
volumes:
    cert_volume:
    acme_challenge:
