services:
    api:
        build: "./server"
        container_name: api
        env_file:
            - /server/.env
        environment:
            - NODE_ENV=production
        ports:
            - 3000:3000
        restart: unless-stopped

    nginx-react:
        build: "./client"
        container_name: nginx-react
        ports:
            - 80:80
        restart: unless-stopped
