services:
    api:
        build: "./server"
        container_name: api
        env_file:
            - server/.env
        environment:
            - NODE_ENV=production
        ports:
            - 3000:3000
        restart: unless-stopped

    nginx-react:
        # build: "./client"
        image: civiaj/nginx-react
        container_name: nginx-react
        # env_file:
        #     -client/.env.production
        ports:
            - 80:80
        restart: unless-stopped
