FROM node:22-alpine as build
WORKDIR /app
EXPOSE 3000
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
RUN cp -r src/email-templates dist
RUN rm -rf src
RUN rm tsconfig.json
ENTRYPOINT [ "node", "dist/index.js" ]
